name: CI/CD Pipeline 
run-name: Continuous_Integration

on: 
  push: 
    branches: ['master']
    
jobs:
  Building_app:
    name: Building the app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '12'

      - name: Set up java environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

# Compiling our web app which in our case is DVWA
      - name: Installing requirements 
        run: |
          sudo apt update
          sudo apt install -y apache2 mariadb-server mariadb-client php php-mysqli php-gd libapache2-mod-php

      - name: Starting apache server
        run: |
          cd DVWA
          sudo service apache2 start 
          cp config/config.inc.php.dist config/config.inc.php 

      # - name: Creating database
      #   run: |
      #     cd DVWA
      #     sudo mariadb -u root;
      #     create database dvwa;
      #     drop user dvwa@localhost;
      #     flush privileges;
      #     create user dvwa@localhost identified by 'p@assw0rd';
      #     grant all on dvwa.* to dvwa@localhost;
      #     flush privileges;
      #     exit;
      #     sudo mariadb -u dvwa -p p@ssw0rd;
      #     source ~/DVWA/databases/create_mssql_db.sql;
      #     exit;

# After the build of our web app, we are ready to perform our first DAST tool scan 
# Modify the file example.js depending on the needs of the scan you want to perform
  Building_DAST_Tool:
    name: Building DAST_Tool
    needs: Setting_up_zap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Running DAST tool readily available as a docker image
        run: |
          cd DAST_Tool/mern-app 
          docker-compose up

  Setting_up_zap:
    name: Setting OWASP ZAP API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Running ZAP as a daemon 
        run: |
          docker pull owasp/zap2docker-stable
          chmod +x zap.sh
          ./zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
  Performing_first_scan:  
    name: Performing first scan
    needs: Setting_up_zap
    runs-on: ubuntu-latest      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Performing scan
        run: |
          cd DAST_Tool/mern-app/zapscanner
          node example.js

      # - name: Install Dependencies 
      #   run: |
      #     cd WebGoat
      #     chmod +x mvnw
      #     ./mvnw clean install

      # - name: Build Docker image locally
      #   run: |
      #     cd WebGoat
      #     chmod +x mvnw
      #     docker build -f Dockerfile . -t webgoat/webgoat 

      # - name: Run the project  
      #   run: |
      #     cd WebGoat
      #     chmod +x mvnw
      #     ./mvnw spring-boot:run
      